/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import dominio.Funcionario;
import dominio.Sistema;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emiliano Marotta 187884 - Sebastian Borjas 303433
 */
public class VentanaRegistrarFuncionario extends javax.swing.JFrame {

    private Sistema sistema;
    private Util util;

    public Util getUtil() {
        return util;
    }

    /**
     * Creates new form VentanaRegistrarArticulo
     */
    public VentanaRegistrarFuncionario(Sistema s) {
        this.sistema = s;
        this.util = new Util();
        initComponents();
        actualizarVentana();
    }

    public Sistema getSistema() {
        return sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaFuncionarios = new javax.swing.JTable();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionarios");

        lblNombre.setText("Nombre");

        lblEdad.setText("Edad");

        txtNombre.setNextFocusableComponent(txtEdad);

        txtEdad.setNextFocusableComponent(txtNumero);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tableListaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Numero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListaFuncionarios.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tableListaFuncionarios);
        tableListaFuncionarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableListaFuncionarios.getColumnModel().getColumnCount() > 0) {
            tableListaFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            tableListaFuncionarios.getColumnModel().getColumn(1).setResizable(false);
            tableListaFuncionarios.getColumnModel().getColumn(2).setResizable(false);
        }

        lblNumero.setText("Numero");

        txtNumero.setNextFocusableComponent(btnAgregar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblEdad)
                            .addComponent(lblNumero))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtEdad)
                            .addComponent(txtNumero))))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdad))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero))
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (this.getUtil().nombreValido(txtNombre.getText())) {
            String nombreFuncionario = txtNombre.getText();

            if (this.getUtil().esNumeroValido(txtEdad.getText())) {

                int edadFuncionario = Integer.parseInt(txtEdad.getText());
                if (this.getUtil().edadFuncionarioValida(edadFuncionario)) {
                    if (this.getUtil().esNumeroValido(txtNumero.getText())) {
                        int numeroFuncionario = Integer.parseInt(txtNumero.getText());
                        if (this.sistema.agregarFuncionario(nombreFuncionario, edadFuncionario, numeroFuncionario)) {
                            //Todo OK:
                            txtNombre.setText("");
                            txtEdad.setText("");
                            txtNumero.setText("");
                            actualizarVentana();
                            JOptionPane.showMessageDialog(this, "Funcionario agregado con éxito", "OK", JOptionPane.INFORMATION_MESSAGE);

                        } else {
                            JOptionPane.showMessageDialog(this, "El funcionario ya está registrado en el sistema", "Error", JOptionPane.ERROR_MESSAGE);

                        }
                    } else {
                        //Numero funcionario invalido
                        JOptionPane.showMessageDialog(this, "El numero de funcionario debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);

                    }

                } else {                    
                    JOptionPane.showMessageDialog(this, "Ingrese una edad válida mayor a 18 y menor a 65", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }

            } else {
                //Numero edad invalido
                JOptionPane.showMessageDialog(this, "La edad debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "El nombre del funcionario debe tener más de 3 caractéres", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTable tableListaFuncionarios;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    public void actualizarVentana() {
        //Obtengo modelo de tabla para manipular datos
        DefaultTableModel modelo = (DefaultTableModel) tableListaFuncionarios.getModel();
        modelo.setRowCount(0);

        for (int i = 0; i < this.getSistema().getListaFuncionarios().size(); i++) {
            //Obtengo funcionarios registrados en sistema
            Funcionario f = this.getSistema().getListaFuncionarios().get(i);

            //Los agrego a la tabla
            String[] fDatos = {f.getNombre(), Integer.toString(f.getEdad()), Integer.toString(f.getNumero())};
            modelo.addRow(fDatos);

        }

    }
}
