/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import archivos.ArchivoLectura;
import dominio.*;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.FileFilter;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emiliano Marotta 187884 - Sebastian Borjas 303433
 */
public class VentanaRegistrarVuelo extends javax.swing.JFrame {
    
    private Sistema sistema;
    
    public VentanaRegistrarVuelo(Sistema s) {
        this.sistema = s;
        UIManager.put("FileChooser.openButtonText", "Abrir");
        UIManager.put("FileChooser.cancelButtonText", "Cancelar");
        UIManager.put("FileChooser.filesOfTypeLabelText", "Tipo");
        UIManager.put("FileChooser.fileNameLabelText", "Archivo");
        UIManager.put("FileChooser.lookInLabelText", "Mirar en");
        initComponents();
        configurarFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFileChooser = new javax.swing.JPanel();
        jFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        lblArea = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVuelo = new javax.swing.JTable();
        lblCoincidencias = new javax.swing.JLabel();
        lblDiferencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser.setDialogTitle("");
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFileChooserLayout = new javax.swing.GroupLayout(panelFileChooser);
        panelFileChooser.setLayout(panelFileChooserLayout);
        panelFileChooserLayout.setHorizontalGroup(
            panelFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFileChooserLayout.createSequentialGroup()
                .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        panelFileChooserLayout.setVerticalGroup(
            panelFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFileChooserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblArea.setText("Area: ");

        lblFila.setText("Fila: ");

        jTableVuelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "De", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVuelo);
        if (jTableVuelo.getColumnModel().getColumnCount() > 0) {
            jTableVuelo.getColumnModel().getColumn(0).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(1).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(2).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(3).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(4).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(5).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(6).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(7).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(8).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(9).setResizable(false);
            jTableVuelo.getColumnModel().getColumn(10).setResizable(false);
        }

        lblCoincidencias.setText("Total coincidencias: ");

        lblDiferencias.setText("Total diferencias: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblArea)
                        .addGap(64, 64, 64)
                        .addComponent(lblFila))
                    .addComponent(lblDiferencias)
                    .addComponent(lblCoincidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(lblFila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCoincidencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiferencias)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("ApproveSelection")) {
            
            ArchivoLectura archivo = new ArchivoLectura(jFileChooser.getSelectedFile().getAbsolutePath());
            ArrayList<String> lineasArchivo = new ArrayList<>();
            //Guardamos las lineas en una lista para ver si es un vuelo valido
            while (archivo.hayMasLineas()) {
                lineasArchivo.add(archivo.linea());
            }
            if (lineasArchivo.size() != 12) {
                JOptionPane.showMessageDialog(this, "Vuelo no exitoso", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String codigoDron = lineasArchivo.get(0);
                //obtener dron
                String[] areaFila = lineasArchivo.get(1).split("#");
                String areas = "ABCDE";
                String letraArea = areaFila[0];
                int coincidencias = 0;
                int diferencias = 0;
                int numeroArea = areas.indexOf(letraArea);
                int fila = Integer.parseInt(areaFila[1]) - 1;
                //Anadir vuelo al dron
                Carga[] filaCargaManual = this.sistema.getListaAreas()[numeroArea].getCargas()[fila];
                //
                DefaultTableModel modelo = (DefaultTableModel) jTableVuelo.getModel();
                modelo.setRowCount(0);
                centrarTextoTabla();
                String[] codCargasManuales = new String[11];
                String[] codCargasArchivo = new String[11];
                codCargasArchivo[0] = "Archivo";
                codCargasManuales[0] = "Manual";
                for (int i = 2; i < lineasArchivo.size(); i++) {
                    int codigoCargaArchivo = Integer.parseInt(lineasArchivo.get(i));
                    int codigoCargaManual = filaCargaManual[i - 2].getCodigo();
                    if (codigoCargaManual == codigoCargaArchivo) {
                        coincidencias++;
                    } else {
                        diferencias++;
                    }
                    codCargasManuales[i - 1] = "" + codigoCargaManual;
                    codCargasArchivo[i - 1] = "" + codigoCargaArchivo;
                }
                modelo.addRow(codCargasArchivo);
                modelo.addRow(codCargasManuales);
                colorearTabla(modelo);
                lblCoincidencias.setText(lblCoincidencias.getText() + coincidencias);
                lblDiferencias.setText(lblDiferencias.getText() + diferencias);
                
            }

            /* 
                Capturar archivo
                Leerlo
                Compararlo con la fila ya ingresada
                Mostrar resultados en la tabla
             */
        } else if (evt.getActionCommand().equals("CancelSelection")) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Se ejecuto una acción no controlada", "Error", JOptionPane.INFORMATION_MESSAGE);
            
        }
        

    }//GEN-LAST:event_jFileChooserActionPerformed
    
    public void centrarTextoTabla() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTableVuelo.setDefaultRenderer(String.class, centerRenderer);
    }
    
    public void colorearTabla(DefaultTableModel modelo) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        
        for (int i = 1; i < 11; i++) {
            Component c = jTableVuelo.getComponentAt(0, i);
            if (modelo.getValueAt(0, i).equals(modelo.getValueAt(1, i))) {
                c.setBackground(Color.red);
                jTableVuelo.getComponentAt(1, i).setBackground(Color.GREEN);
            }
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVuelo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCoincidencias;
    private javax.swing.JLabel lblDiferencias;
    private javax.swing.JLabel lblFila;
    private javax.swing.JPanel panelFileChooser;
    // End of variables declaration//GEN-END:variables

    private void configurarFileChooser() {
        jFileChooser.setCurrentDirectory(new java.io.File("."));
        //Elimina All Files
        jFileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos.txt", "txt");
        jFileChooser.setFileFilter(filter);
    }
}
